// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RasmusLabb1.Contexts;

namespace RasmusLabb1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220405121007_datetimework")]
    partial class datetimework
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmployeeLeaveApplication", b =>
                {
                    b.Property<int>("EmployeesEmloyeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveApplicationsLeaveId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesEmloyeeId", "LeaveApplicationsLeaveId");

                    b.HasIndex("LeaveApplicationsLeaveId");

                    b.ToTable("EmployeeLeaveApplication");
                });

            modelBuilder.Entity("RasmusLabb1.Entities.Employee", b =>
                {
                    b.Property<int>("EmloyeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmloyeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RasmusLabb1.Entities.LeaveApplication", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ApplicationCreated")
                        .HasColumnType("DateTime");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("LeaveReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DateTime");

                    b.HasKey("LeaveId");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("EmployeeLeaveApplication", b =>
                {
                    b.HasOne("RasmusLabb1.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmloyeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasmusLabb1.Entities.LeaveApplication", null)
                        .WithMany()
                        .HasForeignKey("LeaveApplicationsLeaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
